<?php
/**
 * @name IndexController
 * @author root
 * @desc 默认控制器
 * @see http://www.php.net/manual/en/class.yaf-controller-abstract.php
 */

class NewsController extends Base {

    public static $_news = null;

    /**
     * 默认动作
     * Yaf支持直接把Yaf_Request_Abstract::getParam()得到的同名参数作为Action的形参
     * 对于如下的例子, 当访问http://yourhost/demo/index/index/index/name/root 的时候, 你就会发现不同
     */

    public function init()
    {
        if(self::$_news == null){
            self::$_news = new NewsModel();
        }
        return parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $name = $this->getRequest()->getParam("name",'');
        if($name){
            switch($name){
                case "news-list";
                    $this->newslist();
                    break;
                case "ajaxtables";
                    $this->ajaxtables();
                    break;

            }

        }

        Yaf\Dispatcher::getInstance()->autoRender(FALSE);

    }



    //显示文件列表页面
    public function newslist(){
        $o_new = self::$_news;
        $attr = $o_new->attribute();
        if($attr){
            $this->assign('attr',$attr);
        }
        $this->display('news/news-list.phtml');
    }
    //获取表格数据
    public function ajaxtables(){

        $o_new = self::$_news;
        $sWhere = '';
        if($sWhere){
            $sWhere = array();
        }
        $list = $o_new->newsList($sWhere);
        //4.遍历数据资源
        foreach ($list['result'] as $arow){
            $row=array();
            //键关联数组变为索引数组
            $row[] = '<label class="pos-rel"><input id="navid" class="ace" name="n_id[]" value="'.$arow['n_id'].'" type="checkbox"><span class="lbl"></span></label>';
            $row[] = $arow['n_id'];
            $row[] = '<a href="" target="_blank" title="">'.$arow['news_titleshort'].'</a>';
            $row[] = '<a href="" target="_blank" title="食品公司网站">'.$arow['news_columnid'].'</a>';
            $news_flag = $arow['news_flag'];
            if($news_flag){
                if(strstr($arow['news_flag'],'h')){
                    $row[] = '<span style="color:#03C">头</span>';
                }else if(strstr($arow['news_flag'],'c')){
                    $row[] = '<span style="color:#060">荐</span>';
                }else if(strstr($arow['news_flag'],'f')){
                    $row[] = '<span style="color:#09F">幻</span>';
                }else if(strstr($arow['news_flag'],'a')){
                    $row[] = '<span style="color:#09F">幻</span>';
                }else if(strstr($arow['news_flag'],'s')){
                    $row[] = '<span style="color:#C0C">滚</span>';
                }else if(strstr($arow['news_flag'],'p')){
                    $row[] = '<span style="color:#960">图</span>';
                }else if(strstr($arow['news_flag'],'j')){
                    $row[] = '<span style="color:#C00">跳</span>';
                }else if(strstr($arow['news_flag'],'d')){
                    $row[] = '<span style="color:#630">原</span>';
                }else if(strstr($arow['news_flag'],'cp')){
                    $row[] = '<span style="color:#438eb9">产</span>';
                }
            }
            $row[] = $arow['news_hits'];
            if($arow['news_open'] == 1){
                $row[] =  '<a class="red state-btn" href="/news-news_state.html" data-id="'.$arow['n_id'].'" title="已审"><div id="zt'.$arow['n_id'].'"><button class="btn btn-minier btn-yellow">已审</button></div></a>';
            }else{
                $row[] =  '<a class="red state-btn" href="/news-news_state.html" data-id="'.$arow['n_id'].'" title="未审"><div id="zt'.$arow['n_id'].'"><button class="btn btn-minier btn-danger">未审</button></div></a>';
            }
            $time = !empty($arow['news_time'])?$arow['news_time']:time();
            $row[] = date('Y-m-d', $time);

            $up_str = '<div class="hidden-sm hidden-xs action-buttons">';
			$up_str .='<a class="green" href="" title="修改"><i class="ace-icon fa fa-pencil bigger-130"></i></a>';
            $up_str .='<a class="red confirm-rst-url-btn" data-info="你确定要删除到回收站吗？" href="" title="回收站">';
            $up_str .='<i class="ace-icon fa fa-trash-o bigger-130"></i></a></div>';
            $row[]  = $up_str;
            $list['aaData'][]=$row;
        }
        array_pop($list);//弹出不要数组
        echo json_encode($list);exit;

        Yaf\Dispatcher::getInstance()->autoRender(FALSE);
    }


}
