<?php
/**
 * @name IndexController
 * @author root
 * @desc 默认控制器
 * @see http://www.php.net/manual/en/class.yaf-controller-abstract.php
 */

class SysController extends Base {

    /**
     * 默认动作
     * Yaf支持直接把Yaf_Request_Abstract::getParam()得到的同名参数作为Action的形参
     * 对于如下的例子, 当访问http://yourhost/demo/index/index/index/name/root 的时候, 你就会发现不同
     */

    public function init()
    {
        return parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $name = $this->getRequest()->getParam("name",'');
        if($name){
            switch($name){
                case "profile";
                    $this->profile();
                    break;

            }

        }

        Yaf\Dispatcher::getInstance()->autoRender(FALSE);

    }

    /**
     *站点基本配置
     */

    public function sysAction(){

        $this->display('sys/sys.phtml');

    }


    //
    public function profile(){

        $admin=array();
        $aid = C('SESSION_USER_KEY');
        if (session($aid)) {
            $rs = new AdminModel();
            $admin = $rs->profileUser(session($aid));

            $o_news =new NewsModel();
            $field='news_auto';$alias='tp_count';
            $count = $o_news->newsCount($field,$alias);
            $admin['news_count']=$count[$alias];
        }
        $this->assign('admin', $admin);
        $this->display('sys/profile.phtml');
    }

}
