<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta charset="utf-8" />
    <meta name="author" content="YFCMF">
	<title>YAFONE后台系统管理</title>

	<meta name="description" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

	<!-- bootstrap & fontawesome -->
	<link rel="stylesheet" href="/assets/css/bootstrap.css" />
	<link rel="stylesheet" href="/assets/css/font-awesome.css" />

	<!-- page specific plugin styles -->

	<!-- text fonts -->
	<link rel="stylesheet" href="/assets/css/ace-fonts.css" />

	<!-- ace styles -->
	<link rel="stylesheet" href="/assets/css/ace.css" class="ace-main-stylesheet" id="main-ace-style" />

	<!--[if lte IE 9]>
	<link rel="stylesheet" href="/assets/css/ace-part2.css" class="ace-main-stylesheet" />
	<![endif]-->

	<!--[if lte IE 9]>
	<link rel="stylesheet" href="/assets/css/ace-ie.css" />
	<![endif]-->

	<!-- inline styles related to this page -->
	<link rel="stylesheet" href="/assets/css/yfcmf.css" />
	<!-- ace settings handler -->
</head>

<body class="no-skin">
<!-- #section:basics/navbar.layout -->
<div id="navbar" class="navbar navbar-default    navbar-collapse navbar-fixed-top">
	<div class="navbar-container" id="navbar-container">
		<!-- #section:basics/sidebar.mobile.toggle -->
		<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
			<span class="sr-only">Toggle sidebar</span>

			<span class="icon-bar"></span>

			<span class="icon-bar"></span>

			<span class="icon-bar"></span>
		</button>

		<!-- /section:basics/sidebar.mobile.toggle -->
		<div class="navbar-header pull-left">
			<!-- #section:basics/navbar.layout.brand -->
			<a href="<?php echo U('Index/index')?>" class="navbar-brand">
				<small>
					<i class="fa fa-leaf"></i>
					YAFONE系统
				</small>
			</a>

			<!-- /section:basics/navbar.layout.brand -->

			<!-- #section:basics/navbar.toggle -->
			<button class="pull-right navbar-toggle navbar-toggle-img collapsed" type="button" data-toggle="collapse" data-target=".navbar-buttons">
				<span class="sr-only">Toggle user menu</span>
				<?php
				$admin_avatar = C('SESSION_ADMIN_AVATAR');
				$admin_username = C('SESSION_ADMIN_USERNAME');
				if(session($admin_avatar)){
					echo ' <img class="nav-user-photo" src="__UPLOAD__avatar/'.session($admin_username).'" alt="'.session('admin_username').'" />';
				}else{
					echo ' <img class="nav-user-photo" src="/website/index/img/girl.jpg" alt="'.session($admin_username).'" />';
				}
				?>
			</button>

			<!-- /section:basics/navbar.toggle -->
		</div>

		<!-- #section:basics/navbar.dropdown -->
		<div class="navbar-buttons navbar-header pull-right  collapse navbar-collapse" role="navigation">
			<ul class="nav ace-nav">
				<li class="transparent"></li>
				<li class="transparent">
					<a style="cursor:pointer;" class="dropdown-toggle" href="/home-index.html" target="_blank">前台首页</a>
				</li>
				<li class="transparent">
					<a style="cursor:pointer;" data-info="确定要清理缓存吗？" class="dropdown-toggle confirm-rst-btn" href="/sys-clear.html">清除缓存</a>
				</li>
				<li class="transparent" style="display: none">
					<a data-toggle="dropdown" class="dropdown-toggle" href="javascript:void(0);">
						<i class="ace-icon fa fa-bell icon-animated-bell"></i>
					</a>

					<div class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
						<div class="tabbable">
							<ul class="nav nav-tabs">
								<li class="active">
									<a data-toggle="tab" href="#navbar-tasks">
										Tasks
										<span class="badge badge-danger">4</span>
									</a>
								</li>

								<li>
									<a data-toggle="tab" href="#navbar-messages">
										Messages
										<span class="badge badge-danger">5</span>
									</a>
								</li>
							</ul><!-- .nav-tabs -->

							<div class="tab-content">
								<div id="navbar-tasks" class="tab-pane in active">
									<ul class="dropdown-menu-right dropdown-navbar dropdown-menu">
										<li class="dropdown-content">
											<ul class="dropdown-menu dropdown-navbar">
												<li>
													<a href="javascript:void(0);">
														<div class="clearfix">
															<span class="pull-left">Software Update</span>
															<span class="pull-right">65%</span>
														</div>

														<div class="progress progress-mini">
															<div style="width:65%" class="progress-bar"></div>
														</div>
													</a>
												</li>

											</ul>
										</li>

										<li class="dropdown-footer">
											<a href="javascript:void(0);">
												See tasks with details
												<i class="ace-icon fa fa-arrow-right"></i>
											</a>
										</li>
									</ul>
								</div><!-- /.tab-pane -->

								<div id="navbar-messages" class="tab-pane">
									<ul class="dropdown-menu-right dropdown-navbar dropdown-menu">
										<li class="dropdown-content">
											<ul class="dropdown-menu dropdown-navbar">
												<li>
													<a href="javascript:void(0);">
														<img src="" class="msg-photo" alt="Fred's Avatar" />
														<span class="msg-body">
															<span class="msg-title">
																<span class="blue">Fred:</span>
																Vestibulum id penatibus et auctor  ...
															</span>

															<span class="msg-time">
																<i class="ace-icon fa fa-clock-o"></i>
																<span>10:09 am</span>
															</span>
														</span>
													</a>
												</li>
											</ul>
										</li>

										<li class="dropdown-footer">
											<a href="inbox.html">
												See all messages
												<i class="ace-icon fa fa-arrow-right"></i>
											</a>
										</li>
									</ul>
								</div><!-- /.tab-pane -->
							</div><!-- /.tab-content -->
						</div><!-- /.tabbable -->
					</div><!-- /.dropdown-menu -->
				</li>


				<!-- #section:basics/navbar.user_menu -->
				<li class="light-blue">
					<a data-toggle="dropdown" href="javascript:void(0);" class="dropdown-toggle">
						<?php
						$admin_avatar = C('SESSION_ADMIN_AVATAR');
						$admin_username = C('SESSION_ADMIN_USERNAME');
						if(session($admin_avatar)){
							echo ' <img class="nav-user-photo" src="__UPLOAD__avatar/'.session($admin_username).'" alt="'.session('admin_username').'" />';
						}else{
							echo ' <img class="nav-user-photo" src="/website/index/img/girl.jpg" alt="'.session($admin_username).'" />';
						}
						?>
						<span class="user-info">
							<small>Welcome,</small>
							<?php echo session('admin_username')?>
						</span>

						<i class="ace-icon fa fa-caret-down"></i>
					</a>

					<ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">

						<li>
							<a href="/sys-profile.html">
								<i class="ace-icon fa fa-user"></i>
								会员中心
							</a>
						</li>

						<li class="divider"></li>

						<li>
							<a href="/login-logout.html"  data-info="你确定要退出吗？" class="confirm-btn">
								<i class="ace-icon fa fa-power-off"></i>
								注销
							</a>
						</li>
					</ul>
				</li>

				<!-- /section:basics/navbar.user_menu -->
			</ul>
		</div>

		<!-- /section:basics/navbar.dropdown -->
	</div><!-- /.navbar-container -->
</div>