<div class="row">
	<div class="col-xs-12">
		<div class="">
			<div id="sidebar2" class="sidebar h-sidebar navbar-collapse collapse collapse_btn">
				<ul class="nav nav-list header-nav" id="header-nav">

					<?php

						$m = new AuthModel();
						$auth = new Auth();
						$id_3=$m->GetUsrInfo(array('level'=>2));
						$dataaa = $m->showUsers(array('pid'=>$id_3['pid'],'status'=>1));
						$aid = C('SESSION_USER_KEY');
						foreach ($dataaa as $kkk=>$vvv){
							if(!$auth->check($vvv['name'], session($aid)) && session($aid) != 1){
							unset($dataaa[$kkk]);
							}
						}
						//无下级菜单,则找兄弟菜单
						if(empty($dataaa)){
							$dataaa = $m->GetUsrInfo(array('id'=>$id_3['pid']));
							$dataaa = $m->showUsers(array('pid'=>$dataaa['pid'],'status'=>1));
							foreach($dataaa as $kkk=>$vvv){
								if(!$auth->check($vvv['name'], session($aid)) && session($aid) != 1){
									unset($dataaa[$kkk]);
								}
							}

						}
					?>

					<?php
					 foreach($dataaa as $h => $k){
						echo '<li><a href="'.U($k['name']).'"><o class="font12 rigbg">'.$k['title'].'</o></a><b class="arrow"></b></li>';
					 }

					?>

				</ul><!-- /.nav-list -->
			</div><!-- .sidebar -->
		</div>
	</div><!-- /.col -->
</div><!-- /.row -->